language: cpp

sudo: required
dist: trusty

compiler:
  - clang++
  - g++

before_install:
  - wget http://downloads.sourceforge.net/project/sbml/libsbml/5.13.0/stable/Linux/64-bit/libSBML-5.13.0-Linux-x64.deb
  - sudo dpkg -i libSBML-5.13.0-Linux-x64.deb
  - sh travis.testsuite.xml.sh > $HOME/.testsuite.xml
  - cat $HOME/.testsuite.xml

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64

script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - ctest -V

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - boost-latest
    packages:
      - cmake
      - clang-3.8
      - g++-5
      - gcc-5
      - libxml2-dev
      - libbz2-dev
      - libboost1.55-all-dev
      - oracle-java8-installer
      - ant

cache:
  directories:
    - test/integration/testsuite
    - thirdparty/googletest
